version: '3.8'

services:

  postgres_cliente:
    image: postgres:15
    container_name: postgres_cliente
    environment:
      POSTGRES_DB: cliente_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always

  postgres_cuenta:
    image: postgres:15
    container_name: postgres_cuenta
    environment:
      POSTGRES_DB: cuenta_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    restart: always

  cliente_service:
    build: ./cliente-service
    container_name: cliente_service
    depends_on:
      - postgres_cliente
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_cliente:5432/cliente_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: always

  cuenta_service:
    build: ./cuenta-service
    container_name: cuenta_service
    depends_on:
      - postgres_cuenta
      - cliente_service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_cuenta:5432/cuenta_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      CLIENTE_SERVICE_URL: http://cliente_service:8080
    restart: always